title: Wiskunde Vragen
description: Dé website voor al je brandende wiskunde vragen!
theme: jekyll-theme-cayman
google_analytics: UA-157507939-1
defaults:
  -
    values:
      layout: "default"
      latex: true

page_names: { "afg_lijst": {"desc": "Lijst met afgeleides", "url": "../afgeleides/afgeleides.html"}, "prim_lijst": {"desc": "Lijst met primitieven", "url": "../primitieven/primitieven.html"}, "gonio": {"desc": "Goniometrie", "../gonio/"}, "help_diff": {"desc": "Hoe differentieer ik?", "url": "../afgeleides/differentieren"}, "help_prim": {"desc": "Hoe primitiveer ik?", "url": "../primitiveren/integreren"}, "afg_arctan": {"desc": "De afgeleide van arctan(x)", "url": "../afgeleides/arctanx"}, "afg_arcsin": {"desc": "De afgeleide van arcsin(x)", "url": "../afgeleides/arcsinx"}, "afg_arccos": {"desc": "De afgeleide van arccos(x)", "url": "../afgeleides/arccosx"}, "prim_arcsin": {"desc": "De primitieve van arcsin(x)", "url": "../primitiveren/arcsinx"}, "prim_arccos": {"desc": "De primitieve van arccos(x)", "url": "../primitieven/arccosx"}, "prim_arctan": {"desc": "De primitieve van arctan(x)", "url": "../primitieven/arctanx"}}