defaults:
  - values:
      latex: true
      layout: default
description: "Dé website voor al je brandende wiskundevragen!"
google_analytics: UA-157507939-1
lang: nl_NL
page_names:
  afg_arccos:
    desc: "De afgeleide van arccos(x)"
    url: ../afgeleides/arccosx
  afg_arcsin:
    desc: "De afgeleide van arcsin(x)"
    url: ../afgeleides/arcsinx
  afg_arctan:
    desc: "De afgeleide van arctan(x)"
    url: ../afgeleides/arctanx
  afg_calc:
    desc: "Afgeleide calculator"
    url: ../afgeleides/afgeleide-calculator
  afg_lijst:
    desc: "Lijst van afgeleides"
    url: ../afgeleides/afgeleides
  gonio:
    desc: "Verdubbelingsformules en Goniometrische Identiteiten"
    url: ../gonio/
  havo_rooster:
    desc: "Eindexamenrooster HAVO 2021"
    url: ../examen/havo
  home:
    desc: "Homepagina WiskundeVragen"
    url: ../
  prim_arccos:
    desc: "De primitieve van arccos(x)"
    url: ../primitieven/arccosx
  prim_arcsin:
    desc: "De primitieve van arcsin(x)"
    url: ../primitiveren/arcsinx
  prim_arctan:
    desc: "De primitieve van arctan(x)"
    url: ../primitieven/arctanx
  prim_lijst:
    desc: "Lijst met primitieven"
    url: ../primitieven/primitieven
  roosterpagina:
    desc: "Alle eindexamen roosters 2021"
    url: ../examen/
  vwo_rooster:
    desc: "Eindexamenrooster VWO 2021"
    url: ../examen/vwo
  mavo_rooster:
    desc: "Eindexamenrooster VMBO GL en TL 2021"
    url: ../examen/vmbo-gl-tl
  wisk:
    desc: "Wiskunde overzichtspagina"
    url: ../wiskunde
theme: jekyll-theme-cayman
title: "Wiskunde Vragen"
plugins:
  - jekyll-redirect-from