title: Wiskunde Vragen
description: Dé website voor al je brandende wiskunde vragen!
theme: jekyll-theme-cayman
google_analytics: UA-157507939-1
defaults:
  -
    values:
      layout: "default"
      latex: true

options: {"a": "Hallo", "b": "doei", "c": "groetjes"}
choice: "b"