defaults:
  - values:
      latex: true
      layout: default
      lang: nl
description: "Dé website voor al je brandende wiskundevragen!"
google_analytics: UA-157507939-1
lang: nl_NL
page_names:
  afg_arccos:
    desc: "De afgeleide van arccos(x)"
    url: ../afgeleides/arccosx
  afg_arcsin:
    desc: "De afgeleide van arcsin(x)"
    url: ../afgeleides/arcsinx
  afg_arctan:
    desc: "De afgeleide van arctan(x)"
    url: ../afgeleides/arctanx
  afg_calc:
    desc: "Afgeleide calculator"
    url: ../afgeleides/afgeleide-calculator
  afg_lijst:
    desc: "Lijst van afgeleides"
    url: ../afgeleides/afgeleides
  en_afg_calc:
    desc: "Derivative calculator"
    lang: "en_GB"
    url: ../en/derivative-calculator
  en_binom_calc:
    desc: "Binomial coefficient calculator"
    lang: "en_GB"
    url: ../en/binomial-calculator
  en_prim_calc:
    desc: "Integral calculator"
    lang: "en_GB"
    url: ../en/integral-calculator
  gonio:
    desc: "Verdubbelingsformules en Goniometrische Identiteiten"
    url: ../gonio/
  havo_rooster:
    desc: "Examenrooster HAVO 2021"
    url: ../examen/havo
  havo_rooster_1:
    desc: "Examenrooster HAVO 2021 Eerste Tijdvak"
    url: ../examen/havo-1
  havo_rooster_2:
    desc: "Examenrooster HAVO 2021 Tweede Tijdvak"
    url: ../examen/havo-2
  havo_rooster_3:
    desc: "Examenrooster HAVO 2021 Derde Tijdvak"
    url: ../examen/havo-3
  home:
    desc: "Homepagina WiskundeVragen"
    url: ../
  mavo_rooster:
    desc: "Examenrooster VMBO GL en TL 2021"
    url: ../examen/vmbo-gl-tl
  mavo_rooster_1:
    desc: "Examenrooster VMBO GL en TL 2021 Eerste Tijdvak"
    url: ../examen/vmbo-gl-tl-1
  mavo_rooster_2:
    desc: "Examenrooster VMBO GL en TL 2021 Tweede Tijdvak"
    url: ../examen/vmbo-gl-tl-2
  mavo_rooster_3:
    desc: "Examenrooster VMBO GL en TL 2021 Derde Tijdvak"
    url: ../examen/vmbo-gl-tl-3
  prim_arccos:
    desc: "De primitieve van arccos(x)"
    url: ../primitieven/arccosx
  prim_arcsin:
    desc: "De primitieve van arcsin(x)"
    url: ../primitieven/arcsinx
  prim_arctan:
    desc: "De primitieve van arctan(x)"
    url: ../primitieven/arctanx
  prim_calc:
    desc: "Primitieven calculator"
    url: ../primitieven/primitieven-calculator
  prim_lijst:
    desc: "Lijst met primitieven"
    url: ../primitieven/primitieven
  roosterpagina:
    desc: "Alle eindexamen roosters 2021"
    url: ../examen/
  vwo_rooster:
    desc: "Examenrooster VWO 2021"
    url: ../examen/vwo
  vwo_rooster_1:
    desc: "Examenrooster VWO 2021 Eerste Tijdvak"
    url: ../examen/vwo-1
  vwo_rooster_2:
    desc: "Examenrooster VWO 2021 Tweede Tijdvak"
    url: ../examen/vwo-2
  vwo_rooster_3:
    desc: "Examenrooster VWO 2021 Derde Tijdvak"
    url: ../examen/vwo-3
  wisk:
    desc: "Wiskunde overzichtspagina"
    url: ../wiskunde
theme: jekyll-theme-cayman
title: "Wiskunde Vragen"
plugins:
  - jekyll-redirect-from